### PR TITLE
test: add tests for enum

### LINKED ISSUE #129: Test for enum
Please, add test for enum parsing.

### PR DESCRIPTION
**Pull request by ifedchankau**
Add tests for enum in full parsing test

Closes #129

### CODE REVIEW

**Review by romanrostislavovich — APPROVED** [review]
LGTM

**Comment by ifedchankau** [comment]
@binore yes, we will fix it in one of next PR, because it is not a part of this issue.

**Review by romanrostislavovich — APPROVED** [review]
+1

**Pull request merged**
