### PR TITLE
refactor: refactor splitSection function

### LINKED ISSUE #34: Refactoring of splitSection function
Function splitSection of handle.js looks unclear, it's hard to undestand it logic. Please, do refactoring.

### PR DESCRIPTION
**Pull request by romanrostislavovich**
Refactored `splitSection` and all dependencies for it

Closes #34

### CODE REVIEW

**Review by xferra — DISMISSED** [review]
+1

**Comment by svoboda-rabstvo** [comment]
I resolved conflicts

**Comment by romanrostislavovich** [comment]
I resolved conflicts

**Review by ghost — COMMENTED** [review]
Fix merge conflicts

**Review by ghost — APPROVED** [review]

**Pull request merged**
